nameOverride: ""
fullnameOverride: ""

replicaCount: 3

image:
  repository: graymansion/devops-info-service
  tag: "lab02"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

containerPort: 5000

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "5000"
  - name: DEBUG
    value: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

probes:
  liveness:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 3
  startup:
    httpGet:
      path: /health
      port: http
    periodSeconds: 3
    failureThreshold: 20

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

hooks:
  enabled: true
  image:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent
  preInstall:
    weight: -5
    command: "echo Running pre-install validation for devops-info && sleep 3 && echo Pre-install validation done"
  postInstall:
    weight: 5
    command: "echo Running post-install smoke check for devops-info && sleep 3 && echo Post-install smoke check done"